on: [push]

jobs:
  cc26xx-slip-radio-launchpad:
    runs-on: ubuntu-latest
    name: Building cc26xx-slip-radio
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Build Contiki radio for launchpad
      uses: xanderhendriks-uts/action-build-contiki@v2
      with:
        which-project: 'slip-radio'
        which-target: 'launchpad'
    - name: Archive the artifacts
      uses: actions/upload-artifact@v1
      with:
        name: slip-radio-launchpad
        path: examples/ipv6/slip-radio/slip-radio.bin
